/* DATABASE USER ACCESS */
GRANT ALL ON TA_Hunter.* TO 'TA_Hunter'@'localhost' IDENTIFIED BY 'web_sys_dev_user';

/* DATABASE CREATION */
DROP DATABASE IF EXISTS TA_Hunter;
CREATE DATABASE TA_Hunter;
USE TA_Hunter;

/* TABLE CREATION */
DROP TABLE IF EXISTS users;
CREATE TABLE users(
	email VARCHAR(255) NOT NULL,
	firstName VARCHAR(255),
	lastName VARCHAR(255),
	isAdmin BOOL NOT NULL,
	isDispatcher BOOL NOT NULL,
	isDriver BOOL NOT NULL,
    isFirstTime BOOL NOT NULL,
	PRIMARY KEY(email)
);

DROP TABLE IF EXISTS passwords;
CREATE TABLE passwords(
	email VARCHAR(255) NOT NULL,
	password VARCHAR(255),
	PRIMARY KEY(email),
	FOREIGN KEY(email) REFERENCES users(email)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);


